[font]
size = 14
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[font.bold]]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[font.italic]]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[font.bold_italic]]
family = "JetBrainsMono Nerd Font"
style = "Regular"
