[font]
size = 14

[[font.normal]]
family = ["JetBrains Mono Nerd Font"]
style = "Regular"

[[font.bold]]
family = ["JetBrains Mono Nerd Font"]
style = "Regular"

[[font.italic]]
family = ["JetBrains Mono Nerd Font"]
style = "Regular"

[[font.bold_italic]]
family = ["JetBrains Mono Nerd Font"]
style = "Regular"



