theme = "gruber-darker-different"

[editor]
line-number = "relative"
mouse = false
# cursorline = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "separator", "file-name"]
center = ["spinner"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "|" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

"S-h" = ":buffer-previous"
"S-l" = ":buffer-next"

"C-h" = "jump_backward"
"C-l" = "jump_forward"
"C-j" = "save_selection"

"S-d" = "goto_prev_diag"
"S-f" = "goto_next_diag"

x = [ "extend_to_line_bounds", "select_mode" ]

"S-j" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
"S-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]

[keys.insert]
up = "no_op"
down = "no_op" 
left = "no_op" 
right = "no_op"

[keys.select]
x = [ "extend_line" ]
