[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "--line-length", "88", "-"] }
auto-format = true
roots = ["pyproject.toml", "setup.py"]
file-types = ["py"]
indent = { tab-width = 4, unit = "    " }
language-servers = ["pylsp", "ruff", "pyright"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"
# Don't ignore PEP8 error E501 (line too long)
#[language-server.ruff.config.settings]
#args = ["--ignore", "E501"]
